name: Java CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        java: [ 7, 8, 11, 17, 19 ]

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
        cache: 'maven'
    - name: Set up GCS Maven Central mirror
      run: echo "<settings><mirrors><mirror><id>google-maven-central</id><name>GCS Maven Central mirror</name><url>https://maven-central.storage-download.googleapis.com/maven2/</url><mirrorOf>central</mirrorOf></mirror></mirrors></settings>" > ~/.m2/settings.xml
    - name: java -version
      run: java -version
    - name: mvn -version
      run: mvn -version
    - name: Build
      run: mvn -B package --file pom.xml -DskipTests
    - name: Test
      run: mvn -B verify --file pom.xml
